version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.9
executors:
  default:
    docker:
      - image: circleci/golang:1.12-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make test

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: make dist
      - persist_to_workspace:
          root: dist
          paths:
              - "*.tar.gz"
      - store_artifacts:
          path: dist

  deploy:
    docker:
        - image: circleci/python:2.7
    steps:
        - attach_workspace:
            at: dist
        - aws-s3/copy:
            from: "dist/*"
            to: "s3://mattermost-plugins-ci/ci/"
            arguments: "--acl public-read"

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
      - build
      - deploy:
          context: plugin-ci
          requires:
            - lint
            - test
            - build
