version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@volatile

workflows:
  ci-build:
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - plugin-ci/build
      - plugin-ci/deploy-ci:
          filters:
            branches:
              only:
                - master
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/test
            - plugin-ci/build
      - plugin-ci/deploy-release:
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^v.*/
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/test
            - plugin-ci/build
